//# pattern-1, witnesses: 14
@@
@@
- AMDGPU_GEM_CREATE_CPU_ACCESS_REQUIRED
+ AMDGPU_GEM_CREATE_CPU_ACCESS_REQUIRED | AMDGPU_GEM_CREATE_VRAM_CONTIGUOUS
//# pattern-4, witnesses: 2
@@
@@
- AMDGPU_GEM_CREATE_NO_CPU_ACCESS | AMDGPU_GEM_CREATE_SHADOW
+ AMDGPU_GEM_CREATE_NO_CPU_ACCESS | AMDGPU_GEM_CREATE_SHADOW | AMDGPU_GEM_CREATE_VRAM_CONTIGUOUS
