//# pattern-3, witnesses: 5
@@
@@
- TCM_LOGICAL_UNIT_COMMUNICATION_FAILURE
+ TCM_INSUFFICIENT_REGISTRATION_RESOURCES
//# pattern-2, witnesses: 3
@@
@@
- TCM_INVALID_PARAMETER_LIST
+ TCM_INSUFFICIENT_REGISTRATION_RESOURCES
