//# pattern-3, witnesses: 8
@@
@@
- SWITCHDEV_ATTR_PORT_PARENT_ID
+ SWITCHDEV_ATTR_ID_PORT_PARENT_ID
//# pattern-4, witnesses: 4
@@
@@
- SWITCHDEV_ATTR_PORT_BRIDGE_FLAGS
+ SWITCHDEV_ATTR_ID_PORT_BRIDGE_FLAGS
//# pattern-1, witnesses: 3
@@
@@
- SWITCHDEV_ATTR_PORT_STP_STATE
+ SWITCHDEV_ATTR_ID_PORT_STP_STATE
//# pattern-2, witnesses: 2
@@
@@
- SWITCHDEV_ATTR_UNDEFINED
+ SWITCHDEV_ATTR_ID_UNDEFINED
